name: gh-set-secret
on:
  push:
    branches:
      - main

jobs:
  gh-set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        env:
          pat_token: ${{ secrets.PAT_TOKEN }}

        shell: bash
        run: gh auth login --with-token <<< $pat_token

      - name: gh secret set env
        env:
          secret_name: HELLO_WORLD
          secret_body: "Hello World!"
        shell: bash
        run: |
          repository='${{ github.repository }}'
          gh secret set "$secret_name" --body "$secret_body" --repo $repository

      - name: echo secret
        shell: bash
        env:
          secret: ${{ secrets.HELLO_WORLD }}
        run: |
          echo "Secret: $secret"