name: Push Image To Docker-Hub
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/service-images
          tags: latest
          registry: docker.io
          platform: linux/arm64
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Add github actions IP to security group
        env:
          AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
          sleep 10

      - id: retrieve-ipv4
        name: Retrieve Public Ipv4 from Ec2
        env:
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          ip=$(aws --region ${{ env.AWS_REGION }} ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text)
          echo "::add-mask::$ip"
          echo "ipv4=$ip" >> "$GITHUB_OUTPUT"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ steps.retrieve-ipv4.outputs.ipv4 }}
          username: ${{ secrets.USERNAME  }}
          key: ${{ secrets.SSH_PRIVATE_KEY  }}
          script: |
            rm -rf /home/ubuntu/aws-demo
            git clone https://github.com/BalasubramanianSelvarajan/aws-demo.git
            cd aws-demo
            git checkout main
            git pull origin main
            sudo chmod +x ./pre-deploy.sh
            ./pre-deploy.sh
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/service-images:latest
            sudo docker run -p 8080:8080 -d ${{ secrets.DOCKER_USERNAME }}/service-images:latest

      - name: Remove github actions IP from security group
        env:
          AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
        if: always()
      
